"""
scratch/test_document_upload.py
===============================
Integration test for FastAPI Document Ingestion Endpoint and Tier 2 Extraction:
- Uploads synthetic document to POST /api/v1/documents/upload
- Verifies physical file persistence in data/vault/documents/
- Verifies background extraction populates data/macro_liquidity.json
- Verifies GET /api/v1/liquidity/state
- Verifies POST /api/v1/liquidity/promotional-debt
- Verifies duplicate detection via SHA-256
"""

import sys
import io
import time
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from api.server import build_app, EngineContext
from fastapi.testclient import TestClient


def run_tests():
    print("=== Running FastAPI Document Ingestion & Liquidity Integration Tests ===")
    
    ctx = EngineContext()
    app = build_app(ctx)
    client = TestClient(app)

    # 1. Test GET /api/v1/liquidity/state baseline
    print("\n--- Test 1: GET /api/v1/liquidity/state Baseline ---")
    resp = client.get("/api/v1/liquidity/state")
    assert resp.status_code == 200, f"Expected 200, got {resp.status_code}"
    state_json = resp.json()
    assert state_json["success"] is True
    assert "state" in state_json
    print(f"[PASS] Baseline state retrieved: Net Buffer=${state_json['state']['net_collateral_buffer']}")

    # 2. Test POST /api/v1/documents/upload with synthetic PDF content
    print("\n--- Test 2: POST /api/v1/documents/upload ---")
    fake_pdf_content = b"%PDF-1.4\n1 0 obj\n<< /Title (Experian Credit Disclosure) >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF"
    files = {
        "file": ("sample_credit_disclosure.pdf", io.BytesIO(fake_pdf_content), "application/pdf")
    }
    data = {
        "doc_type": "CREDIT_REPORT"
    }

    upload_resp = client.post("/api/v1/documents/upload", files=files, data=data)
    assert upload_resp.status_code == 200, f"Upload failed: {upload_resp.text}"
    upload_json = upload_resp.json()
    assert upload_json["success"] is True
    assert upload_json["status"] == "QUEUED"
    saved_path = Path(upload_json["path"])
    print(f"[PASS] Document upload enqueued successfully. Saved path: {saved_path}")

    # Verify physical file existence in data/vault/documents
    assert saved_path.exists(), f"File {saved_path} does not exist on disk!"
    assert saved_path.read_bytes() == fake_pdf_content, "Persisted bytes do not match uploaded bytes!"
    print(f"[PASS] File persistence verified on disk ({saved_path.stat().st_size} bytes)")

    # TestClient in FastAPI runs background tasks synchronously upon response completion
    # Verify data/macro_liquidity.json was generated and atomically written
    state_file = Path("data/macro_liquidity.json")
    assert state_file.exists(), f"{state_file} was not generated by extraction task!"
    persisted_state = json.loads(state_file.read_text())
    assert "credit_report" in persisted_state
    assert "collateral_state" in persisted_state
    assert persisted_state["sha256"] != ""
    print(f"[PASS] Extraction generated macro_liquidity.json with SHA-256: {persisted_state['sha256'][:16]}...")

    # 3. Test duplicate upload detection via SHA-256
    print("\n--- Test 3: Duplicate Upload Detection via SHA-256 ---")
    files_dup = {
        "file": ("sample_credit_disclosure_dup.pdf", io.BytesIO(fake_pdf_content), "application/pdf")
    }
    upload_dup_resp = client.post("/api/v1/documents/upload", files=files_dup, data=data)
    assert upload_dup_resp.status_code == 200
    print("[PASS] Duplicate upload safely ingested and recognized as duplicate by SHA-256")

    # 4. Test POST /api/v1/liquidity/promotional-debt (manual entry)
    print("\n--- Test 4: POST /api/v1/liquidity/promotional-debt Manual Entry ---")
    promo_payload = {
        "id": "promo_citi_simplicity_001",
        "institution": "Citi Simplicity",
        "total_balance": 2840.00,
        "promotional_apr": 0.0,
        "expiration_date": "2026-12-15",
        "minimum_monthly_payment": 60.00,
        "notes": "0% APR Balance Transfer Promo"
    }
    promo_resp = client.post("/api/v1/liquidity/promotional-debt", json=promo_payload)
    assert promo_resp.status_code == 200, f"Promo debt creation failed: {promo_resp.text}"
    promo_json = promo_resp.json()
    assert promo_json["success"] is True
    assert promo_json["promotional_debt"]["institution"] == "Citi Simplicity"
    print(f"[PASS] Manual promotional debt created. New buffer: ${promo_json['new_state']['net_collateral_buffer']}")

    # 5. Test GET /api/v1/liquidity/credit-report
    print("\n--- Test 5: GET /api/v1/liquidity/credit-report ---")
    cr_resp = client.get("/api/v1/liquidity/credit-report")
    assert cr_resp.status_code == 200
    cr_json = cr_resp.json()
    assert cr_json["success"] is True
    assert "tradelines" in cr_json["credit_report"]
    print(f"[PASS] Credit report retrieved. Tradelines count: {len(cr_json['credit_report']['tradelines'])}")

    print("\n>>> ALL INGESTION AND LIQUIDITY INTEGRATION TESTS PASSED! <<<\n")


if __name__ == "__main__":
    run_tests()
